name: BAFSync
version: 1.0.0
main: eu.bierandfriends.bafsync.BAFSync
api-version: 1.20
description: Verknüpft Minecraft-Accounts mit der BierAndFriends App
author: RicoDessau

commands:
  biersync:
    description: Verknüpfe deinen Minecraft-Account mit der BAF App
    usage: /biersync <Token>
    permission: bafsync.use
    permission-message: "§cDu hast keine Berechtigung für diesen Befehl."

permissions:
  bafsync.use:
    description: Erlaubt die Nutzung von /biersync
    default: true
